hmpps-auth:
  url: "http://localhost:8090/auth"

spring:
  datasource:
    url: 'jdbc:h2:mem:iis-db;MODE=MSSQLServer;INIT=CREATE SCHEMA IF NOT EXISTS HPA'
    username: iis
    password: dummy

  flyway:
    locations: classpath:db/migration
    enabled: true
