generic-service:
  nameOverride: hmpps-historical-prisoner-api
  productId: "DPS065"
  replicaCount: 4

  image:
    repository: quay.io/hmpps/hmpps-historical-prisoner-api
    tag: app_version # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: historical-prisoner-api-cert
    modsecurity_enabled: true
    modsecurity_snippet: |
      SecRuleEngine On
      # team here grants access to the OpenSearch logs to delve into the cause of the blockage
      SecDefaultAction "phase:2,pass,log,tag:github_team=syscon-devs,tag:namespace={{ .Release.Namespace }}"
      # Default is only GET HEAD POST OPTIONS so need to include PUT etc.
      SecAction "id:900200,phase:1,nolog,pass,t:none,setvar:tx.allowed_methods=GET HEAD POST OPTIONS PUT PATCH DELETE,setvar:tx.paranoia_level=3"
      # Need to allow % in the URL for searching for prisoners (URL Encoding Abuse Attack Attempt)
      SecRuleRemoveById 920220
      # Searching for prisoners gives Invalid character in request (outside of printable chars below ascii 127) so remove
      SecRuleRemoveById 920272
      # Change default denial to be a 406 so that we can tell easily that it is modsecurity doing the blocking
      SecRuleUpdateActionById 949110 "t:none,deny,status:406,logdata:%{SERVER_NAME}"
      SecRuleUpdateActionById 959100 "t:none,deny,status:406,logdata:%{SERVER_NAME}"

  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json

  namespace_secrets:
    application-insights:
      APPLICATIONINSIGHTS_CONNECTION_STRING: "APPLICATIONINSIGHTS_CONNECTION_STRING"
    rds-sqlserver-instance-output:
      DATABASE_ENDPOINT: "DB_SERVER"
      DATABASE_USERNAME: "DB_USER"
      DATABASE_PASSWORD: "DB_PASS"

  allowlist:
    groups:
      - internal

generic-prometheus-alerts:
  targetApplication: hmpps-historical-prisoner-api
