generic-service:
  nameOverride: hmpps-historical-prisoner-api
  productId: "DPS065"
  replicaCount: 4

  image:
    repository: quay.io/hmpps/hmpps-historical-prisoner-api
    tag: app_version # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: hmpps-historical-prisoner-api-cert

  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY)"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json

  namespace_secrets:
    hmpps-historical-prisoner-api:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"

  allowlist:
    groups:
      - internal

generic-prometheus-alerts:
  targetApplication: hmpps-historical-prisoner-api
