---
generic-service:
  replicaCount: 2

  ingress:
    host: historical-prisoner-api-preprod.prison.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: "applicationinsights.dev.json"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    DATABASE_NAME: "iis-preprod"

  scheduledDowntime:
    enabled: true
    startup: '50 6 * * 1-5' # Start at 6.50am UTC Monday-Friday
    shutdown: '50 20 * * 1-5' # Stop at 8.40pm UTC Monday-Friday

generic-prometheus-alerts:
  businessHoursOnly: true
  alertSeverity: syscon-nonprod
