---
# Per environment values which override defaults in hmpps-historical-prisoner-api/values.yaml

generic-service:
  ingress:
    host: hmpps-historical-prisoner-api.hmpps.service.justice.gov.uk

  env:
    API_BASE_URL_OAUTH: https://sign-in.hmpps.service.justice.gov.uk/auth

# CloudPlatform AlertManager receiver to route promethues alerts to slack
generic-prometheus-alerts:
  alertSeverity: hmpps_tech
