create table HPA.HDC_RECALL
(
    PK_HDC_RECALL   int identity
        constraint PK_HDC_RECALL
            primary key,
    PRISON_NUMBER   varchar(8) not null,
    CREATED_DATE    date,
    CURFEW_END_DATE date,
    OUTCOME_DATE    date,
    OUTCOME         varchar(28),
    REASON          varchar(28)
);

create index HPA_HDC_RECALL
    on HPA.HDC_RECALL (PRISON_NUMBER, CREATED_DATE);

INSERT INTO HPA.HDC_RECALL (PK_HDC_RECALL, PRISON_NUMBER, CREATED_DATE, CURFEW_END_DATE, OUTCOME_DATE, OUTCOME, REASON) VALUES (1, N'AB111111', N'2001-01-01', N'2001-01-02', N'2001-01-02', N'Licence revoked: recalled', N'BREACH CONDITIONS 38A1(a)');
INSERT INTO HPA.HDC_RECALL (PK_HDC_RECALL, PRISON_NUMBER, CREATED_DATE, CURFEW_END_DATE, OUTCOME_DATE, OUTCOME, REASON) VALUES (2, N'AB111111', N'2001-01-04', N'2001-01-05', N'2001-01-02', N'Re-released following recall', N'CHANGE OF CIRCS 38A1(b)');
INSERT INTO HPA.HDC_RECALL (PK_HDC_RECALL, PRISON_NUMBER, CREATED_DATE, CURFEW_END_DATE, OUTCOME_DATE, OUTCOME, REASON) VALUES (3, N'AB111112', N'2001-01-02', N'2001-01-03', N'2001-01-02', N'Licence breach: rec rejected', N'INABILITY & CHARGE 38A1(b)');
