name: Build and test kotlin

on:
  workflow_call:
    inputs:
      java_version:
        type: string
        required: false
        default: '21'
      java_options:
        type: string
        default: '-Xmx512m -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2 -Dorg.gradle.daemon=false -Dkotlin.compiler.execution.strategy=in-process'
        required: false

permissions:
  contents: read

jobs:
  kotlin-validate:
    name: Validate the Kotlin app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Refresh cache
        id: initial-cache
        uses: actions/cache@v4
        env:
          cache-name: kotlin-cache
        with:
          path: |
            - gradle-{{ checksum "build.gradle.kts" }}
            - gradle-
          key: ${{ runner.os }}-gradle-${{ env.cache-name }}-${{ hashFiles('build.gradle.kts') }}

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '${{ inputs.java_version }}'
          cache: 'gradle'
          cache-dependency-path: |
            *.gradle*
            **/gradle-wrapper.properties

      - name: Run tests
        shell: bash
        run: |
          export JAVA_OPTS="${{ inputs.java_options }}"
          ./gradlew check

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            build/test-results/test
            build/reports/tests/test

  report:
    name: Report test results
    runs-on: ubuntu-latest
    needs: kotlin-validate
    steps:
      - name: Download test results
        uses: actions/download-artifact@v4
        with:
          name: test-results
          path: test-results

      - name: Publish test report
        uses: dorny/test-reporter@v2
        with:
          name: JUnit Tests
          artifact: test-results
          path: test-results/**/*.xml
          reporter: java-junit
