name: Security OWASP dependency check
on:
  workflow_dispatch:
  schedule:
    - cron: "48 8 * * MON-FRI" # Every weekday
jobs:
  security-kotlin-owasp-check:
    name: Kotlin security OWASP dependency check
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/security_owasp.yml@v0.7 # WORKFLOW_VERSION
    with:
      channel_id: C06KY7GLF3L
    secrets: inherit
